image: node:latest

stages:
  - install
  - build
  - quality
  - deploy

cache:
  paths:
    - node_modules/
    - build/

install:
  stage: install
  script:
    - yarn

build:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - build

lint:
  stage: quality
  script:
    - yarn lint

test:
  stage: quality
  script:
    - yarn test:coverage

pages:
  stage: deploy
  script:
    - rm -rf public
    - mv build public
    - du public -a -h | sort -hr
  artifacts:
    paths:
      - public
  only:
    - master
